Py1809Project/iceberg/cars/urls.py
from .import views
from django.conf.urls import url

urlpatterns = [
        url(r'^addCar/$', views.addCar, name='addCar'),
        url(r'^carorder/$', views.carorder, name='carorder'),
        url(r'^updatelist/$', views.updatelist, name='updatelist'),
        url(r'^myorder/$', views.myorder, name='myorder'),
        url(r'^paysgoods/$', views.paysgoods, name='paysgoods'),
    ]

Py1809Project/iceberg/iceberg/urls.py
from django.conf.urls import url, include
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^iceberg/', include('users.urls',namespace='users')),
    url(r'^iceberg/', include('store.urls',namespace='store')),
    url(r'^iceberg/', include('goods.urls',namespace='goods')),
    url(r'^iceberg/', include('cars.urls',namespace='cars')),
]

Py1809Project/iceberg/users/urls.py
from .import views
from django.conf.urls import url

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^register/$', views.register, name='register'),
    url(r'^logins/$', views.logins, name='logins'),
    url(r"^active/$", views.actives, name="active"),
    url(r"^yanzheng/$", views.yanzheng, name="yanzheng"),
    url(r"^userinfor/$", views.userinfor, name="userinfor"),
    url(r"^updateuser/$", views.updateuser, name="updateuser"),
    url(r"^baseinfo/$", views.baseinfo, name="baseinfo"),
    url(r"^createstore/$", views.createstore, name="createstore"),
    url(r"^addaddress/$", views.addaddress, name="addaddress"),
    url(r"^updateaddre/$", views.updateaddre, name="updateaddre"),
    url(r"^ordered/$", views.ordered, name="ordered"),
    url(r"^quite/$", views.quite, name="quite"),
]

Py1809Project/iceberg/users/models.py
from django.db import models

import datetime

# Create your models here.
class Usersmanage(models.Manager):
    def Create_user(self, name, pwd, email):
        user = self.create(pickname=name, pwd=pwd, email=email)
        user.save()


class Users(models.Model):
    id = models.AutoField(primary_key=True)
    pickname = models.CharField(max_length=20, verbose_name='昵称')
    pwd = models.CharField(max_length=50, verbose_name='密码')
    email = models.EmailField( verbose_name='邮箱')
    adress = models.CharField(max_length=100, blank=True, verbose_name='地址')
    phone = models.CharField(max_length=11,blank=True)
    catime = models.DateTimeField(verbose_name='注册时间', auto_now_add=True)
    header = models.ImageField(upload_to='static/upload/head', verbose_name='头像', default='static/upload/head/header.png')
    usermanage = Usersmanage()

class Address(models.Model):
    id = models.AutoField(primary_key=True)
    adress = models.CharField(max_length=100, blank=True, verbose_name='地址')
    adfor = models.ForeignKey(Users, on_delete=models.CASCADE)

Py1809Project/iceberg/users/views.py
from django.shortcuts import render, HttpResponse, redirect

# 导入事务模块
from django.db import transaction
from . import models


# 导入加密
import hashlib

# 邮箱验证
from django.conf import settings
from django.core.mail import send_mail

# 验证码导入模块
from io import BytesIO
from . import utils


# 用于序列化Django对象的接口
from django.core.serializers import serialize, deserialize
from django.http import JsonResponse


# 导入缓存
from django.core.cache import cache


# 导入分页模块
from django.core.paginator import Paginator
from django.conf import settings


# 导入商品和商店类
from goods.models import goods
from store.models import stores

from cars.models import shoplist
# Create your views here.


# 主页
def index(request):
    # 判断缓存是否含有goodsall
    goodsall = cache.get('goodsall')
    if goodsall is None:
        stores2 = stores.objects.filter(states=True)
        goodsall =[]
        for i in stores2:
            goodsall.extend(goods.objects.filter(warestatus=True,forgoo=i))
        cache.set('goodsall', goodsall, 60*5)
    # 分页
    pagesize = settings.PAGESIZE
    paginator = Paginator(goodsall, pagesize)
    # 获取当前页的页码
    pagenum = request.GET.get('pagenum', default=1)
    page = paginator.page(int(pagenum))
    return render(request, 'index.html',{'paginator':paginator, 'page':page})




from random import Random



def phone_regist(request):
    return render(request, 'users/phone_regist.html')

# 邮箱注册验证码
def em_code():
    # 生成随机字符串
    str = ''
    chars = 'AaBbCcDdEeFfGgHhIiJjKkLlMmNnOoPpQqRrSsTtUuVvWwXxYyZz0123456789'
    length = len(chars) - 1
    random = Random()
    for i in range(8):
        str += chars[random.randint(0, length)]
    return str


# 注册
def register(request):
    if request.method == 'GET':
        return render(request, 'users/register.html')
    elif request.method == 'POST':
        password = request.POST['password']
        confirm_password = request.POST['confirm_password']
        pickname = request.POST['pickname']
        email = request.POST['email']
        if password != confirm_password:
            return render(request, 'users/register.html', {'msg': "两次密码不一致"})
        user = models.Users.usermanage.filter(pickname=pickname)
        if user.exists():
            return render(request, 'users/register.html', {'msg': "该用户名已存在，请重新注册"})
        else:
            m_title = "iceberg冰山欢迎你，来吧!"
            m_msg = em_code()
            try:
                send_mail(m_title, m_msg, settings.EMAIL_FROM, [email])
            except Exception as e:
                print(e,66666)
            md = hashlib.md5()
            md.update(password.encode('utf8'))
            pwd = md.hexdigest()
            request.session['mailcode'] = m_msg
            request.session['pickname'] = pickname
            request.session['email'] = email
            request.session['pwd'] = pwd
            return render(request, 'users/email_active.html', {'msg': '激活码已发至你邮箱'})


# 激活，注册成功
def actives(request):
    if request.method == 'POST':
        # 防止重复激活
        try:
            if request.POST['emcode'] == request.session['mailcode']:
                # 添加新用户
                user = models.Users(pickname=request.session['pickname'], pwd=request.session['pwd'],
                                    email=request.session['email'])
                user.save()
                request.session.delete()
                return render(request, 'users/email_active.html', {'msg': '注册成功'})
            else:
                return render(request, 'users/email_active.html', {'msg': '验证码错误，请重试'})
        except:
            return render(request, 'users/email_active.html')
    else:
        return render(request, 'index.html')


# def reg_email(request):
#     m_title = "赵电商账号激活邮件"
#     m_msg = "点击激活您的账号"
#     send_mail(m_title, m_msg, settings.EMAIL_FROM, ['1304895886@qq.com'])
#     return render(request, "users/register.html", {"msg": "恭喜您，注册成功，请登录邮箱激活账号！！"})


# 生成验证码
def yanzheng(request):
    # 在内存中开辟空间用以生成临时的图片
    f = BytesIO()
    img, code = utils.create_code()
    # 保存验证码信息到 session 中，方便下次表单提交时进行验证操作
    request.session['check_code'] = code
    img.save(f, 'PNG')
    return HttpResponse(f.getvalue())


from django.forms.models import model_to_dict
# 用于序列化Django对象的接口
from django.core.serializers import serialize, deserialize

# 引入店类
from store.models import stores



# 登录
def logins(request):
    # 超链接访问
    if request.method == 'GET':
        return render(request, 'users/logins.html')
    elif request.method == 'POST':
        yanzh = request.session['check_code']
        if yanzh != request.POST["code"]:
            return render(request, 'users/logins.html', {'msg': '验证码错误'})
        username = request.POST['username']
        users = models.Users.usermanage.filter(pickname=username)
        if users.exists():
            user = users.first()
            pwds = request.POST['pwd']
            md = hashlib.md5()
            md.update(pwds.encode('utf8'))
            pwds = md.hexdigest()
            if user.pwd == pwds:
                request.session['user'] = user
                return redirect('users:index')
            else:
                msg = '密码错误'
        else:
            msg = '用户名不存在'
        return render(request, 'users/logins.html', {'msg': msg})



# 展示用户信息
def userinfor(request):
    # 判断有没有登陆
    if 'user' not in request.session:
        return redirect('users:logins')
    store1 = stores.objects.filter(masters=request.session['user'])
    if store1.exists():
        request.session['storelis'] = store1
    return render(request, 'users/userinfor.html')



# 完善会员信息
def updateuser(request):
    if request.method == 'GET':
        return render(request, 'users/updateuser.html')
    elif request.method == 'POST':
        phone = request.POST['phone']
        diqu = request.POST['diqu']
        province = request.POST['province']
        city = request.POST['city']
        qu = request.POST['qu']
        intro = request.POST['intro']
        address = diqu + province + city + qu + intro
        user = request.session['user']
        user.adress = address
        user.phone = phone
        try:
            header = request.FILES['header']
            user.header = header
        except:
            pass
        user.save()
        request.session['user'] = user

        request.session['storelis'] = stores.objects.filter(masters=user)
        return redirect('users:userinfor')


# 添加地址，并默认
def addaddress(request):
    if request.method == 'GET':
        return render(request,'users/addaddress.html')
    # 添加
    elif request.method == 'POST':
        diqu = request.POST['diqu']
        province = request.POST['province']
        city = request.POST['city']
        qu = request.POST['qu']
        intro = request.POST['intro']
        address = diqu + province + city + qu + intro
        user = request.session['user']
        temp = user.adress
        # 将新增地址设为默认地址
        user.adress = address
        user.save()
        address1 = models.Address(adfor=user, adress=temp)
        address1.save()
        # 判断有没有登陆
        if 'user' not in request.session:
            return redirect('users:logins')
        # 更新session
        request.session['user'] = user
        request.session['storelis'] = stores.objects.filter(masters=user)
        request.session['addresslis'] = models.Address.objects.filter(adfor=user)
        return redirect('cars:myorder')


# 改为默认地址
def updateaddre(request):
    newaddr = models.Address.objects.get(id=int(request.GET['sid']))
    user = request.session['user']
    temp = user.adress
    print(temp)
    user.adress = newaddr.adress
    user.save()
    newaddr.adress = temp
    newaddr.save()
    request.session['user'] = user
    request.session['addresslis'] = models.Address.objects.filter(adfor=user)
    return redirect('cars:myorder')


# 修改基本信息
def baseinfo(request):
    if request.method == 'GET':
        return render(request, 'users/baseinfo.html')
    elif request.method == 'POST':
        pickname = request.POST['pickname']
        email = request.POST['email']
        oripassword = request.POST['oripassword']
        password1 = request.POST['password1']
        password2 = request.POST['password2']
        if password1 != password2:
            return render(request, 'users/baseinfo.html', {'msg': '两次输入新密码不一致'})
        md = hashlib.md5()
        md.update(oripassword.encode('utf8'))
        pwds = md.hexdigest()
        user = request.session['user']
        if user.pwd == pwds :
            user.pickname=pickname
            user.email=email
            if password1 != '':
                md = hashlib.md5()
                md.update(password1.encode('utf8'))
                pwds1 = md.hexdigest()
                user.pwd = pwds1
            user.save()
            request.session['user']=user
            return redirect('users:userinfor')
        else:
            return render(request, 'users/baseinfo.html', {'msg': '密码错误'})


# 开店
def createstore(request):
    # 验证登陆
    if 'user' not in request.session:
        return redirect('users:logins')
    if request.method == 'GET':
        user = request.session['user']
        print(type(user.phone))
        if user.adress == '' or user.phone == '':
            return render(request, 'users/userinfor.html', {'msg': '请先完善个人信息'})
        else:
            return render(request, 'users/createstore.html')
    elif request.method == 'POST':
        storename = request.POST['storename']
        storeimg = request.FILES['storeimg']
        info = request.POST['info']
        store1 = stores(storename=storename, storeinfo=info, storephoto=storeimg, masters=request.session['user'])
        store1.save()
        store2 = stores.objects.filter(masters=request.session['user'])
        request.session['storelis'] = store2
        return render(request, 'users/userinfor.html', {'msg': '您好没上架商品，去您的店铺看看吧'})


# 推出
def quite(request):
    request.session.delete()
    return redirect('users:index')

def ordered(request):
    # 判断有没有登陆

Py1809Project/iceberg/users/templates/users/addaddress.html
{% extends 'users/register.html' %}

{% block register %}
{% load static %}
<script type="text/javascript" src="/static/js/addr.js"></script>
<h3>添加地址</h3>
<form action="{% url 'users:addaddress' %}" method="post">
    {% csrf_token %}
    <div class="form-group">
        地区：<select id="area" required name="diqu"></select>
        省：<select id="cmbProvince" required name="province"></select>
        市：<select id="cmbCity" required name="city"></select>
        区：<select id="cmbArea" required  name="qu"></select>
        <br/><br/>
        <p>详细地址：<input type="text" required name="intro"></p>
    </div>

    <button type="submit" class="btn btn-default">提交</button>
</form>
{{msg}}

{% endblock %}

{% block script %}
<script type="text/javascript">
addressInit('area', 'cmbProvince', 'cmbCity', 'cmbArea', '西北地区', '北京', '市辖区', '东城区');

</script>
{% endblock %}

Py1809Project/iceberg/users/templates/users/baseinfo.html
{% extends 'users/register.html' %}

{% block register %}
{% load static %}
<script type="text/javascript" src="/static/js/addr.js"></script>
<h3>基本信息</h3>
<form action="{% url 'users:baseinfo' %}" method="post">
    {% csrf_token %}
    <div class="form-group">
        <label></label>
        <input type="text" autocomplete="off"  class="form-control" maxlength=20 placeholder="昵称" name="pickname" required value={{request.session.user.pickname}}>
    </div>
    <div class="form-group">
        <label for="inputEmail3" class="col-sm-2 control-label">邮箱</label>
        <div class="col-sm-10">
          <input type="email" class="form-control" autocomplete="off" id="inputEmail3" required name="email" value={{request.session.user.email}}>
        </div>
      </div>

      <div class="form-group">
        <label class="col-sm-2 control-label">原始密码</label>
        <div class="col-sm-10">
          <input type="password" class="form-control" minlength=6 maxlength=12 autocomplete="off"  required name="oripassword" value="">
        </div>
     </div>
    <div class="form-group">
        <label class="col-sm-2 control-label">新密码</label>
        <div class="col-sm-10">
          <input type="password" class="form-control" minlength=6 maxlength=12 autocomplete="off"  placeholder="可选" name="password1" value="">
        </div>
     </div>
    <div class="form-group">
        <label class="col-sm-2 control-label">再次输入密码</label>
        <div class="col-sm-10">
          <input type="password" class="form-control" minlength=6 maxlength=12 autocomplete="off" name="password2" value="">
        </div>
     </div>
    <button type="submit" class="btn btn-default" onclick="return confirm('是否确定修改')">修改</button>
</form>
{{msg}}
{% endblock %}

{% block script %}
<script type="text/javascript">

</script>
{% endblock %}

Py1809Project/iceberg/users/templates/users/createstore.html
{% extends 'users/register.html' %}

{% block register %}
{% load static %}
<script type="text/javascript" src="/static/js/addr.js"></script>
<h3>店铺申请</h3>
<form action="{% url 'users:createstore' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="form-group">
        <label>店铺名字</label>
        <input type="text" autocomplete="off"  class="form-control" maxlength=20 required name="storename" value="">
    </div>
    <div class="form-group">
        <label for="exampleInputFile">门店图片</label>
        <input type="file" required id="exampleInputFile" name="storeimg" value="">
    </div>
    <div class="form-group">
        <label >店铺信息</label>
        <textarea id="" required cols="30" rows="10" name="info" maxlength=96></textarea>
    </div>
    <button type="submit" class="btn btn-default">提交</button>
</form>

{{msg}}

{% endblock %}

{% block script %}
<script type="text/javascript">
addressInit('area', 'cmbProvince', 'cmbCity', 'cmbArea', '西北地区', '北京', '市辖区', '东城区');

</script>
{% endblock %}

Py1809Project/iceberg/users/templates/users/email_active.html
{% extends 'users/register.html' %}
{% block register %}
<form class="form-inline" action="{% url 'users:active' %}" method="post">
    {% csrf_token %}
    <div class="form-group">
    <label class="sr-only" for="exampleInputAmount">Amount (in dollars)</label>
    <div class="input-group">
      <div class="input-group-addon">激活码</div>
      <input type="text" autocomplete="off" class="form-control" name="emcode" id="exampleInputAmount" placeholder="8位">
      <div class="input-group-addon">😃</div>
    </div>
  </div>
  <button type="submit" class="btn btn-primary">激活</button>
</form>
{{msg}}
{% endblock %}

Py1809Project/iceberg/users/templates/users/logins.html
{% extends 'users/register.html' %}

{% block register %}
{% load static %}
<form class="form-horizontal" action="{% url 'users:logins' %}" method="post" >
    {% csrf_token %}
    <div class="form-group">
        <input type="text" required class="form-control col-sm-10" placeholder="用户名" maxlength="50" autocomplete="off" name="username" value="">
    </div>
    <div class="form-group">
        <input type="password" maxlength=12 required class="form-control col-sm-10" id="exampleInputPassword1" placeholder="密码" name="pwd" value="">
    </div>
    <div class="form-group">
        <label  >验证码:</label>
        <input type="text" class="form-control" maxlength="4" autocomplete="off" name="code" value="">
        <img src="{% url 'users:yanzheng' %}" alt="" onclick="refrish(this)"  >
    </div>
    <input type="hidden" name="nexturl" value={{next_url}}>
    <div class="form-group">
        <button type="submit" class="btn btn-default">提交</button>
        <button type="reset" class="btn btn-default">重置</button>
    </div>
</form>
{{msg}}

{% endblock %}

{% block script %}
<script>
    function refrish(node){
            node.src ="/users/yanzheng/?id=" + Math.random();
    }
</script>
{% endblock %}

Py1809Project/iceberg/users/templates/users/ordered.html
{% extends 'users/register.html' %}

{% block register %}
{% load static %}
{% if request.session.user is None %}
您还没登录，去登录吧
{% else %}

<p>我的已完成订单：</p>
    <table class="table table-hover">
        <tr>
            <th>订单</th>
            <th>邮寄地址</th>
            <th>总额</th>
        </tr>
        {% for s in ordered %}
            <tr>
                <td>{{forloop.counter}}</td>
                <th>{{s.goodnumnam}}</th>
                <th>{{s.acount}}</th>
            </tr>

        {% empty %}
        您还没有订单
        {% endfor %}
    </table>

{% endif %}
<br>
<h6 style="color:blue">{{msg}}</h6>

{% endblock %}

Py1809Project/iceberg/users/templates/users/phone_regist.html
{% extends 'users/register.html' %}

{% block register %}


<!--发送按钮倒计时代码-->
<script type="text/javascript">
var countdown=60;
function settime(obj) {
    if (countdown == 0) {
        obj.removeAttribute("disabled");
        obj.value="免费获取验证码";
        countdown = 60;
        return;
    } else {
        obj.setAttribute("disabled", true);
        obj.value="重新发送(" + countdown + ")";
        countdown--;
    }
setTimeout(function() {
    settime(obj) }
    ,1000)
}

</script>


<!--手机号码输入框代码-->
<form class="form-group" action="" method="post">
    {% csrf_token %}
    <label for="mobile" class="col-lg-2 col-sm-2 control-label">手机号码:</label>
    <div class="col-lg-10">
        <div class="input-group m-bot15">
    <input type="text" class="form-control" id="mobile" name="mobile" placeholder="手机号码">
    <span class="input-group-btn">
         <input type="button" id="forcode" onclick="settime(this)" value="免费获取验证码" class="btn btn-success">
    </span>
        </div>
    <p class="help-block">请填写绑定手机号</p>
    </div>
</form>



<!--向后台通过ajax发送手机号码数据-->
<script>
    $('#forcode').click(function () {
        $.ajax({
            cache:false,
            type:"POST",
            url:"{% url 'users:forcode' %}",
            data:{
               mobile:$("#mobile").val()
            },
            async:true,
            success:function (data) {
                alert(data)
            }
        })
    })
</script>

{% endblock %}

Py1809Project/iceberg/users/templates/users/updateuser.html
{% extends 'users/register.html' %}

{% block register %}
{% load static %}
<script type="text/javascript" src="/static/js/addr.js"></script>
<h3 style="color:red;">{{msg}}</h3>
<h5>完善个人信息：</h5>
<form action="{% url 'users:updateuser' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="form-group">
        <label></label>
        <input type="number" autocomplete="off"  class="form-control" maxlength=11 minlength=11 required placeholder="电话" name="phone" value="">
    </div>
    <div class="form-group">
        地区：<select id="area" required name="diqu"></select>
        省：<select id="cmbProvince" required name="province"></select>
        市：<select id="cmbCity" required name="city"></select>
        区：<select id="cmbArea" required  name="qu"></select>
        <br/><br/>
        <p>详细地址：<input type="text" required name="intro"></p>
    </div>
    <div class="form-group">
        <label >头像</label>
        <input type="file"  name="header" value="">
    </div>
    <button type="submit" class="btn btn-default">提交</button>
</form>


{% endblock %}

{% block script %}
<script type="text/javascript">
addressInit('area', 'cmbProvince', 'cmbCity', 'cmbArea', '西北地区', '北京', '市辖区', '东城区');

</script>
{% endblock %}

Py1809Project/iceberg/users/templates/users/userinfor.html
{% extends 'users/register.html' %}

{% block register %}
{% load static %}
{% if request.session.user is None %}
您还没登录，去登录吧
{% else %}
<img width=60 height=60 class="img-circle" src='/{{request.session.user.header}}' alt="">
<table>
    <tr><td>昵称：</td><td>{{request.session.user.pickname}}</td></tr>
    <tr><td>邮箱：</td><td>{{request.session.user.email}}</td></tr>
    <tr><td>地址：</td>
        <td>
            {% if request.session.user.adress == '' %}
                未填
            {% else %}
                {{request.session.user.adress}}
            {% endif %}
        </td>
    </tr>
    <tr><td>手机：</td>
        <td>
            {% if request.session.user.phone == '' %}
                未填
            {% else %}
                {{request.session.user.phone}}
            {% endif %}
        </td>
    </tr>
</table>

<h4><a href="{% url 'users:updateuser' %}">完善个人信息</a></h4>
<h4><a href="{% url 'users:baseinfo' %}">修改基本信息</a></h4>
<h4><a href="{% url 'users:ordered' %}">我的订单</a></h4>
<br>
<p>我的店铺：</p>
            {% for s in request.session.storelis %}
            <a href="/iceberg/mystore/?sid={{s.id}}">{{s.storename}}</a>
            <br>
            {% empty %}
            您还没店铺
            {% endfor %}

{% endif %}
<br>
<h6 style="color:blue">{{msg}}</h6>

{% endblock %}

{% block script %}
<script type="text/javascript">
        addressInit('area', 'cmbProvince', 'cmbCity', 'cmbArea', '西北地区', '北京', '市辖区', '东城区');
        //addressInit('Select1', 'Select2', 'Select3');

</script>
{% endblock %}