Py1809Project/iceberg/cars/urls.py
from .import views
from django.conf.urls import url

urlpatterns = [
        url(r'^addCar/$', views.addCar, name='addCar'),
        url(r'^carorder/$', views.carorder, name='carorder'),
        url(r'^updatelist/$', views.updatelist, name='updatelist'),
        url(r'^myorder/$', views.myorder, name='myorder'),
        url(r'^paysgoods/$', views.paysgoods, name='paysgoods'),
    ]

Py1809Project/iceberg/goods/urls.py
from .import views
from django.conf.urls import url

urlpatterns = [
    url(r'^upgoods/$', views.upgoods, name='upgoods'),
    url(r'^goodsinfo/$', views.goodsinfo, name='goodsinfo'),
    url(r'^updownGoods/$', views.updownGoods, name='updownGoods'),
    url(r'^updategoods/$', views.updategoods, name='updategoods'),
    url(r'^detailinfo/$', views.detailinfo, name='detailinfo'),
    url(r'^single/$', views.single, name='single'),

]

Py1809Project/iceberg/iceberg/urls.py
from django.conf.urls import url, include
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^iceberg/', include('users.urls',namespace='users')),
    url(r'^iceberg/', include('store.urls',namespace='store')),
    url(r'^iceberg/', include('goods.urls',namespace='goods')),
    url(r'^iceberg/', include('cars.urls',namespace='cars')),
]

Py1809Project/iceberg/store/urls.py
from .import views
from django.conf.urls import url

urlpatterns = [
    url(r'^women/$', views.women, name='women'),
    url(r'^men/$', views.men, name='men'),
    url(r'^collection/$', views.collection, name='collection'),
    url(r'^(?P<id>\d+)/addcollect/$', views.addcollect, name='addcollect'),
    url(r'^colldel/$', views.colldel, name='colldel'),
    url(r"^mystore/$", views.mystore, name="mystore"),
    url(r"^updatestore/$", views.updatestore, name="updatestore"),

]

Py1809Project/iceberg/users/urls.py
from .import views
from django.conf.urls import url

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^register/$', views.register, name='register'),
    url(r'^logins/$', views.logins, name='logins'),
    url(r"^active/$", views.actives, name="active"),
    url(r"^yanzheng/$", views.yanzheng, name="yanzheng"),
    url(r"^userinfor/$", views.userinfor, name="userinfor"),
    url(r"^updateuser/$", views.updateuser, name="updateuser"),
    url(r"^baseinfo/$", views.baseinfo, name="baseinfo"),
    url(r"^createstore/$", views.createstore, name="createstore"),
    url(r"^addaddress/$", views.addaddress, name="addaddress"),
    url(r"^updateaddre/$", views.updateaddre, name="updateaddre"),
    url(r"^ordered/$", views.ordered, name="ordered"),
    url(r"^quite/$", views.quite, name="quite"),
]

Py1809Project/iceberg/goods/models.py
from django.db import models
from store.models import stores
from users.models import Users
# Create your models here.


class goods(models.Model):
    id = models.AutoField(primary_key=True)
    waresname = models.CharField(max_length=30,verbose_name='商品名字')
    waresinfo = models.CharField(max_length=200,verbose_name='商品详情')
    waressize = models.CharField(max_length=4,verbose_name='商品尺码')
    waresstock = models.PositiveIntegerField(verbose_name='商品库存',default=0)
    warescount = models.PositiveIntegerField(verbose_name='商品销量',default=0)
    waresprice = models.FloatField(verbose_name='商品价格', max_length=7)
    borntime = models.DateTimeField(verbose_name='上架时间', auto_now_add=True)
    warestatus = models.BooleanField(verbose_name='商品状态',default=True)
    forgoo = models.ForeignKey(stores, on_delete=models.CASCADE)

class category(models.Model):
    id = models.AutoField(primary_key=True)
    category1 = models.CharField(max_length=20,verbose_name='男士/女士')
    category2 = models.CharField(max_length=20,verbose_name='季节')
    forcat = models.ForeignKey(goods, on_delete=models.CASCADE)

class goodsimgs(models.Model):
    id = models.AutoField(primary_key=True)
    imag0 = models.ImageField(upload_to='static/upload/goods', verbose_name='商品图片')
    forimg = models.ForeignKey(goods, on_delete=models.CASCADE)


# 收藏
class cllocter(models.Model):
    id = models.AutoField(primary_key=True)
    goodsid = models.IntegerField(verbose_name='商品id')
    forcll = models.ForeignKey(Users, on_delete=models.CASCADE)

Py1809Project/iceberg/goods/views.py
from django.shortcuts import render, redirect
from . import models
from store.models import stores
from  cars.models import Cars, Orders
from django.core.cache import cache
# Create your views here.


# 上传商品
def upgoods(request):
    if request.method == 'GET':
        return render(request, 'goods/upgoods.html')
    elif request.method=='POST':
        store1 = request.session['store']
        waresname = request.POST['waresname']
        category1 = request.POST['category1']
        category2 = request.POST['category2']
        waresstock = request.POST['waresstock']
        waresprice = request.POST['waresprice']
        waresinfo = request.POST['waresinfo']
        waressize = request.POST['waressize']
        waresprice = float(waresprice)

        ware1 = models.goods(
            waresname=waresname,
            waresstock=waresstock,
            waresprice=waresprice,
            waresinfo=waresinfo,
            waressize=waressize,
            forgoo=store1
            )
        ware1.save()
        categorys = models.category(category1=category1,
                                    category2=category2,
                                    forcat=ware1)
        categorys.save()
        imgstr = ['imag0', 'imag1', 'imag2', 'imag3', 'imag4']
        for i in imgstr:
            try:
                imag0 = request.FILES[i]
                goodsimg = models.goodsimgs(imag0=imag0, forimg=ware1)
                goodsimg.save()
            except:
                pass

            goodsli = models.goods.objects.filter(forgoo=request.session['store'])
            cache.set("goodsli", goodsli)
        # 将商品添加到页面
        goodsall = cache.get('goodsall')
        if goodsall is None:
            stores2 = models.stores.objects.filter(states=True)
            goodsall = []
            for i in stores2:
                goodsall.extend(models.goods.objects.filter(warestatus=True, forgoo=i))
            cache.set('goodsall', goodsall)
        else:
            goodsall.append(ware1)
            cache.set('goodsall', goodsall)
        return render(request, 'store/mystore.html')


# 商家查看商品详情
def detailinfo(request):
    ware1 = models.goods.objects.get(id=int(request.GET['ware1']))
    request.session['ware1'] = ware1
    imgli = models.goodsimgs.objects.filter(forimg=ware1)
    request.session['imgli'] = imgli
    request.session['categorys'] = models.category.objects.get(forcat=ware1)
    return render(request, 'goods/detailinfo.html')


# 商家修改商品信息
def updategoods(request):
    if request.method == 'GET':
        return render(request, 'goods/updategoods.html')
    elif request.method == 'POST':
        waresname = request.POST['waresname']
        waresstock = request.POST['waresstock']
        waresinfo = request.POST['waresinfo']
        waressize = request.POST['waressize']
        waresprice = request.POST['waresprice']

        ware1 = request.session['ware1']
        ware1.waresname = waresname
        ware1.waresstock = waresstock
        ware1.waresinfo = waresinfo
        ware1.waressize = waressize
        ware1.waresprice = waresprice
        ware1.save()
        request.session['ware1'] = ware1
        # 商家修改商品信息，则购物车里信息也做修改
        orders1 = Orders.objects.filter(goodid=ware1.id)
        for i in orders1:
            # 若购物车订单未提交，则修改
            if i.forord.status:
                i.goodname = waresname
                i.goodprice = waresprice
                i.save()
        # 修改图片
        imglis = models.goodsimgs.objects.filter(forimg=ware1)
        imgstr = ['imag0', 'imag1', 'imag2', 'imag3', 'imag4']
        countnum = len(imglis)
        for i in imgstr:
            try:
                imag0 = request.FILES[i]
                goodsimg = models.goodsimgs(imag0=imag0, forimg=ware1)
                goodsimg.save()
                countnum +=1
                if countnum >5 :
                    imglis.first().delete()
            except:
                pass
        return render(request, 'goods/goodsinfo.html')


# 商品的上下架
def updownGoods(request):
    goods1 = models.goods.objects.get(id=int(request.GET['ware']))
    goodsall = cache.get('goodsall')
    if goodsall is None:
        stores2 = models.stores.objects.filter(states=True)
        goodsall = []
        for i in stores2:
            goodsall.extend(models.goods.objects.filter(warestatus=True, forgoo=i))
        cache.set('goodsall', goodsall, 60 * 5)

    if goods1.warestatus:
        goods1.warestatus = False
        # 将商品从页面删除
        if goods1 in goodsall:
            goodsall.remove(goods1)
            cache.set('goodsall', goodsall, 60 * 5)
    else:
        goods1.warestatus = True
        # 将商品添加到页面
        if goods1 not in goodsall:
            goodsall.append(goods1)
            cache.set('goodsall', goodsall, 60 * 5)
    goods1.save()
    goodsli = models.goods.objects.filter(forgoo=request.session['store'])
    cache.set("goodsli", goodsli)
    return redirect('goods:goodsinfo')


# 商家查看商品列表
def goodsinfo(request):
    goodsli = cache.get("goodsli")
    if goodsli is None:
        goodsli = models.goods.objects.filter(forgoo=request.session['store'])
        cache.set("goodsli", goodsli)
    return render(request, 'goods/goodsinfo.html',{'goodsli': goodsli})


# 买家查看商品详情
def single(request):
    ware1 = models.goods.objects.get(id=int(request.GET['seach']))
    request.session['addgoods'] = ware1
    return render(request,'goods/single.html')

Py1809Project/iceberg/goods/templates/goods/detailinfo.html
{% extends 'goods/upgoods.html' %}

{% block ulhead %}
<ul class="nav nav-pills">
    <li role="presentation"><a href="{% url 'users:index' %}">HOME </a></li>
    <li role="presentation"><a href="{% url 'store:mystore' %}">店铺信息 </a></li>
    <li role="presentation"><a href="{% url 'store:mystore' %}">上传商品 </a></li>
    <li role="presentation" class="active"><a href="{% url 'goods:goodsinfo' %}">查看商品列表</a></li>
    </ul>
{% endblock %}

{% block content %}
<br>
    <form action="{% url 'goods:updategoods' %}">
        <button type="submit" class="btn btn-info">修改此商品信息</button>
    </form>
<br>
<table class="table table-bordered" border=1>
    <tr>
        <th>商品名</th>
        <th>库存</th>
        <th>价格(RMB)</th>
        <th>上架时间</th>
        <th>商品类型</th>
        <th>商品尺码</th>
    </tr>
    <tr>
        <td>{{request.session.ware1.waresname}}</td>
        <td>{{request.session.ware1.waresstock}}</td>
        <td>{{request.session.ware1.waresprice}}</td>
        <td>{{request.session.ware1.borntime}}</td>
        <td>
            {{request.session.categorys.category1}}
            {{request.session.categorys.category2}}
        </td>
        <td>{{request.session.ware1.waressize}}</td>
    </tr>
    <tr>
        <td><h4>商品详情:</h4></td>
        <td colspan="5">{{request.session.ware1.waresinfo}}</td>
    </tr>
    <tr>
        <td><h4>商品图片:</h4></td>
        <td colspan="5">
            {% for x in request.session.imgli %}
            <img width=19% height=90% src="/{{x.imag0}}" alt="">
            {% empty %}
            <p>o(︶︿︶)o 唉，还没有图片</p>
            {% endfor %}
        </td>
    </tr>
</table>
<h5>图片最多5张</h5>

{% endblock %}

Py1809Project/iceberg/goods/templates/goods/goodsinfo.html
{% extends 'goods/upgoods.html' %}

{% block ulhead %}
<ul class="nav nav-pills">
    <li role="presentation"><a href="{% url 'users:index' %}">HOME </a></li>
    <li role="presentation"><a href="{% url 'store:mystore' %}">店铺信息 </a></li>
    <li role="presentation"><a href="{% url 'goods:upgoods' %}">上传商品 </a></li>
    <li role="presentation" class="active"><a href="{% url 'goods:goodsinfo' %}">查看商品列表</a></li>
</ul>
{% endblock %}

{% block content %}
<br>
<br>
<table class="table table-hover">
    <tr>
        <th>#</th>
        <th>商品名</th>
        <th>库存</th>
        <th>销量</th>
        <th>价格(RMB)</th>
        <th>状态</th>
        <th>上/下架</th>
    </tr>
    {% for i in goodsli %}
    <tr>
        <td>{{forloop.counter}}</td>
        <td><a href="/iceberg/detailinfo/?ware1={{i.id}}">{{i.waresname}}</a></td>
        <td>{{i.waresstock}}</td>
        <td>{{i.warescount}}</td>
        <td>{{i.waresprice}}</td>
        <td>
            {% if i.warestatus %}
            <h5>上架中</h5>
            {% else %}
            <h5>已下架</h5>
            {% endif %}
        </td>
        <td>
            {% if i.warestatus %}
            <form action="{% url 'goods:updownGoods' %}" method="get">
                <button type="submit" class="btn btn-warning du" name="ware" value={{i.id}}
                        onclick="return confirm('是否确定下架')">下架
                </button>
            </form>
            {% else %}
            <form action="{% url 'goods:updownGoods' %}" method="get">
                <button type="submit" class="btn btn-success du" name="ware" value={{i.id}}
                        onclick="return confirm('是否确定重新上架')">上架
                </button>
            </form>
            {% endif %}
        </td>
    </tr>
    {% empty %}
    <p>☹，还没商品</p>
    {% endfor %}
</table>
{% endblock %}

Py1809Project/iceberg/goods/templates/goods/updategoods.html
{% extends 'goods/upgoods.html' %}

{% block ulhead %}
<ul class="nav nav-pills">
    <li role="presentation"><a href="{% url 'users:index' %}">HOME </a></li>
    <li role="presentation"><a href="{% url 'store:mystore' %}">店铺信息 </a></li>
    <li role="presentation"><a href="{% url 'store:mystore' %}">上传商品 </a></li>
    <li role="presentation"><a href="{% url 'goods:goodsinfo' %}">查看商品列表</a></li>
</ul>
{% endblock %}

{% block content %}
<br>
<br>
<form class="form-horizontal" method="post" enctype="multipart/form-data"
      action="{% url 'goods:updategoods' %}">
    {% csrf_token %}
    <div class="form-group">
        <label class="col-sm-2 control-label">商品名称</label>
        <div class="col-sm-10">
            <input type="text" class="form-control" maxlength=30 name="waresname"
                   value={{request.session.ware1.waresname}}>
        </div>
    </div>
    <div class="form-group">
        <label class="col-sm-2 control-label">商品尺码</label>
        <div class="col-sm-10">
            <input type="text" maxlength=4 class="form-control" required placeholder="必填" name="waressize"
                   value={{request.session.ware1.waressize}}>
        </div>
        <label class="col-sm-2 control-label">商品库存</label>
        <div class="col-sm-10">
            <input type="number" class="form-control" name="waresstock"
                   value={{request.session.ware1.waresstock}}>
        </div>
    </div>
    <div class="form-group">
        <label class="col-sm-2 control-label">商品价格</label>
        <div class="input-group">
            <div class="input-group-addon">
                <span>RMB</span>
            </div>
            <input type="text" class="col-sm-2 form-control " maxlength=7
                   onkeyup="this.value=this.value.toString().match(/^\d+(?:\.\d{0,2})?/)" required
                   placeholder="0.00" name="waresprice" value={{request.session.ware1.waresprice}}>
        </div>
    </div>
    <di class="form-group">
        <label class="col-sm-2 control-label">商品详细信息</label>
        <div class="col-sm-10">
            <textarea class="form-control" rows="3" maxlength=200 name="waresinfo">
                {{request.session.ware1.waresinfo}}
            </textarea>
        </div>
    </di>
    <div class="form-group">
        <label for="exampleInputFile">图片0</label>
        <input type="file" onclick="return confirm('是否确定添加')" id="exampleInputFile" autocomplete="off" placeholder="图片0"
               name="imag0">

    </div>
    <div class="form-group">
        <label for="exampleInputFile1">(可选)图片1</label>
        <input type="file" id="exampleInputFile1" onclick="return confirm('是否确定添加')" autocomplete="off"
               placeholder="图片1" name="imag1">

    </div>
    <div class="form-group">
        <label for="exampleInputFile2">(可选)图片2</label>
        <input type="file" id="exampleInputFile2" onclick="return confirm('是否确定添加')" autocomplete="off"
               placeholder="图片2" name="imag2">

    </div>
    <div class="form-group">
        <label for="exampleInputFile3">(可选)图片3</label>
        <input type="file" id="exampleInputFile3" onclick="return confirm('是否确定添加')" autocomplete="off"
               placeholder="图片3" name="imag3">

    </div>
    <div class="form-group">
        <label for="exampleInputFile4">(可选)图片4</label>
        <input type="file" id="exampleInputFile4" onclick="return confirm('是否确定添加')" autocomplete="off"
               placeholder="图片4" name="imag4">

    </div>

    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <button type="submit" onclick="return confirm('是否确定修改')" class="btn btn-default">上传</button>
        </div>
    </div>
</form>
<br>
{% endblock %}

Py1809Project/iceberg/goods/templates/goods/upgoods.html
<!DOCTYPE html>
<html>

<head>
    <title>iceberg</title>
    {% load static %}
    <script src="{% static 'js/jquery.min.js' %}"></script>


    <!--jQuery (necessary for Bootstrap's JavaScript plugins) -->

    <!-- Custom Theme files -->
    <!--theme-style-->
    <link href="{% static 'css/style.css' %}" rel="stylesheet" type="text/css" media="all"/>
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet" type="text/css" media="all"/>
    <!--//theme-style-->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta name="keywords" content="Fashion Store Responsive web template, Bootstrap Web Templates, Flat Web Templates, Andriod Compatible web template,
Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyErricsson, Motorola web design"/>
    <script type="application/x-javascript">
	addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); }





    </script>
    <!--fonts-->
    <style>
		#dl{
			position:relative;
			left:270px;
		}






    </style>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700,800' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Oswald:400,700,300' rel='stylesheet' type='text/css'>
</head>

<!--//fonts-->
</head>
<body>
<!--header-->
<div class="header">
    <div class="header-top">
        <div class="container">
            <div class="header-grid">
                <ul>
                    <li><a href="#" class="scroll">Articles</a></li>
                    <li><a href="#" class="scroll">Contact </a></li>
                    <li><a href="{% url 'users:userinfor' %}" class="scroll">我的</a></li>
                    <li><a href="#" class="scroll">Terms</a></li>
                </ul>
            </div>
            <div class="header-grid-right" id="dl">
                {% if request.session.user is None %}
                <a href="{% url 'users:logins' %}" class="sign-up">登录</a>
                <label>|</label>
                <a href="{% url 'users:register' %}" class="sign-in">注册</a>
                {% else %}
                <a href="{% url 'users:userinfor' %}" class="scroll"
                   style="color:red">{{request.session.user.pickname}}</a>
                <img width=60 height=60 class="img-circle" src='/{{request.session.user.header}}' alt="">
                <span><a href="{% url 'users:quite' %}" style="color:red">退出</a></span>
                {% endif %}
            </div>
            <div class="clearfix"></div>
        </div>
    </div>
    <div class="container">
        <div class="header-bottom">
            <div class="logo">
                <a href="index.html"><img src="/static/images/logo.png" alt=" "></a>
            </div>
            <div class="ad-right">
                <img src="/static/images/ad.png" alt=" ">
            </div>
            <div class="clearfix"></div>
        </div>
        <div class="header-bottom-bottom">
            <div class="top-nav">
                <span class="menu"> </span>
                {% block ulhead %}
                <ul class="nav nav-pills">
                    <li role="presentation"><a href="{% url 'users:index' %}">HOME </a></li>
                    <li role="presentation"><a href="{% url 'store:mystore' %}">店铺信息 </a></li>
                    <li role="presentation" class="active"><a href="{% url 'goods:upgoods' %}">上传商品 </a></li>
                    <li role="presentation"><a href="{% url 'goods:goodsinfo' %}">查看商品列表</a></li>
                </ul>
                {% endblock %}
                <div class="clearfix"></div>
                <script>
					$("span.menu").click(function(){
						$(".top-nav ul").slideToggle(500, function(){
						});
					});





                </script>
            </div>
            <div class="search">
                <form>
                    <input type="text" value="Search" onfocus="this.value = '';"
                           onblur="if (this.value == '') {this.value = '';}">
                    <input type="submit" value="">
                </form>
            </div>
            <div class="clearfix"></div>
        </div>
    </div>
</div>
<!---->
<div class="content">
    {# 店铺信息、商品列表展示，待完成 #}
    <div class="container">
        {% block content %}
        <div class="register">
            {% block register %}
            <form class="form-horizontal" method="post" enctype="multipart/form-data"
                  action="{% url 'goods:upgoods' %}">
                {% csrf_token %}
                <div class="form-group">
                    <label class="col-sm-2 control-label">商品名称</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" maxlength=30 required placeholder="必填" name="waresname"
                               value="">
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-2 control-label">商品类型</label>
                    <div>
                        <input type="radio" checked name="category1" value="男士">男士
                        <input type="radio" name="category1" value="女士">女士
                        <select name="category2">
                            <option value="冬季">冬季</option>
                            <option value="春季">春季</option>
                            <option value="夏季">夏季</option>
                            <option value="秋季">秋季</option>
                        </select>
                    </div>


                </div>
                <div class="form-group">
                    <label class="col-sm-2 control-label">商品尺码</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" maxlength=4 required placeholder="必填" name="waressize" value="">
                    </div>
                    <label class="col-sm-2 control-label">商品库存</label>
                    <div class="col-sm-10">
                        <input type="number" class="form-control" required placeholder="必填" name="waresstock" value="">
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-2 control-label">商品价格</label>
                    <div class="input-group">
                        <div class="input-group-addon">
                            <span>RMB</span>
                        </div>
                        <input type="text" class="col-sm-2 form-control " maxlength=7
                               onkeyup="this.value=this.value.toString().match(/^\d+(?:\.\d{0,2})?/)" required
                               placeholder="0.00" name="waresprice" value="">
                    </div>
                </div>
                <di class="form-group">
                    <label class="col-sm-2 control-label">商品详细信息</label>
                    <div class="col-sm-10">
                        <textarea class="form-control" rows="3" required maxlength=200 name="waresinfo"></textarea>
                    </div>
                </di>
                <div class="form-group">
                    <label for="exampleInputFile">(必选)图片0</label>
                    <input type="file" id="exampleInputFile" autocomplete="off" placeholder="默认图片" required
                           name="imag0">

                </div>
                <div class="form-group">
                    <label for="exampleInputFile1">(可选)图片1</label>
                    <input type="file" id="exampleInputFile1" autocomplete="off" placeholder="图片1" name="imag1">

                </div>
                <div class="form-group">
                    <label for="exampleInputFile2">(可选)图片2</label>
                    <input type="file" id="exampleInputFile2" autocomplete="off" placeholder="图片2" name="imag2">

                </div>
                <div class="form-group">
                    <label for="exampleInputFile3">(可选)图片3</label>
                    <input type="file" id="exampleInputFile3" autocomplete="off" placeholder="图片3" name="imag3">

                </div>
                <div class="form-group">
                    <label for="exampleInputFile4">(可选)图片4</label>
                    <input type="file" id="exampleInputFile4" autocomplete="off" placeholder="图片4" name="imag4">

                </div>

                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                        <button type="submit" class="btn btn-default">上传</button>
                    </div>
                </div>
            </form>
            {{msg}}
            {% endblock %}
        </div>
        {% endblock %}
    </div>
</div>
</div>
<!---->
<div class="footer">
    <div class="container">
        <div class="footer-class">
            <div class="class-footer">
                <ul>
                    <li><a href="{% url 'users:index' %}">HOME </a></li>
                    <li><a href="{% url 'store:men' %}">男装</a></li>
                    <li><a href="{% url 'store:women' %}">女装</a></li>
                    <li><a href="{% url 'store:collection' %}">时尚</a></li>
                </ul>
                <p class="footer-grid">Copyright &copy; 2015.Company name All rights reserved.More Templates <a
                        href="http://www.cssmoban.com/" target="_blank" title="模板之家">模板之家</a> - Collect from <a
                        href="http://www.cssmoban.com/" title="网页模板" target="_blank">网页模板</a></p>
            </div>
            <div class="footer-left">
                <a href="{% url 'users:index' %}"><img src="{% static 'images/logo1.png' %}" alt=" "/></a>
            </div>
            <div class="clearfix"></div>
        </div>
    </div>
</div>
{% block script %}
<script>

</script>
{% endblock %}
</body>
</html>