Py1809Project/FireFish/Bocke/urls.py
from django.conf.urls import url,include
from django.contrib import admin
# 导入视图
from . import views

urlpatterns = [
    url(r'^$', views.index0),
    url(r'^create/$', views.Create_author),
    url(r'^findall/$', views.findall),
    url(r'^find/$', views.find),
    url(r'^delete/$', views.delete),
    url(r'^update/$', views.update),
    url(r'^(\w+)/param/$', views.param),
    url(r'^(\d+)/param2/$', views.param2),
    url(r'^(?P<username>\w+)/params/$', views.params),
    url(r'^req/$', views.reqmeth),
    url(r'^index1/$', views.index1),
    url(r'^index2/$', views.index2),
    url(r'^index/$', views.index),
    url(r'^login/$', views.login,name="login"),
    url(r'^register/$', views.register,name="register"),
    url(r'^Hans/$', views.logsend,name="Hans"),
    url(r'^success/$', views.registsend,name="success"),
    url(r'^Hans1/$', views.logsuccess,name="Hans1"),
    url(r'^read/$', views.read,name="read"),
    url(r'^writer/$', views.writing,name="writer"),
    ]

Py1809Project/FireFish/FireFish/urls.py
from django.conf.urls import url,include
from django.contrib import admin
# 导入视图
from . import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # url(r'^$', views.index),
    url(r'^xiucd/',include("xiucd.urls")),
    url(r'^Bocke/',include("Bocke.urls",namespace="Bocke"))
]

Py1809Project/FireFish/xiucd/urls.py
from django.conf.urls import url
from django.contrib import admin
# 导入视图
from . import views,views1,views2

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^findall/$', views.findall),
    url(r'^addone/$', views1.addone),
    url(r'^delone/$', views2.delone)
]

Py1809Project/FireFish/xiucd/models.py
from django.db import models

# Create your models here.

Py1809Project/FireFish/FireFish/views.py
from django.http import HttpResponse
from django.shortcuts import render


#  构建反馈方法
def index(request):
    print("+++")
    return HttpResponse("<h1>绣春刀</h1><p>心存侥幸，赌徒是也</p>")

Py1809Project/FireFish/xiucd/views.py
from django.shortcuts import render

# Create your views here.
from django.http import HttpResponse

#  构建反馈方法
def findall(request):
    print("+++")
    return HttpResponse("<p>查询名单</p><p><h1>张三</h1><h1>王武</h1><h1>疯子</h1></p>")

Py1809Project/FireFish/Bocke/templates/Bocke/index1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>汉兰</title>
	<style type="text/css">
		div:{
			width: 100px;
			line-height: 40px;
			margin: 20 auto;
			background-color: gray;
		}
		ul:{
			width: 800px;
			margin: 10px auto;
			list-style-type: none;
		}
		a:{text-align: center;
			margin: 0 auto;
			color: beige;
		}
		h1:{
			margin: 0 auto;
			color: blue;
		}
		
	</style>
</head>
<body>
    <!-- <h1>{{msg}}</h1> -->
	
	<div>
		<h1>万万没想到</h1>
		<ul>
			<li><a href="login.html">登录</a></li>
			<li><a href="register.html">注册</a></li>
		</ul>
		{% load static %}
		<img src="{% static 'Bocke/imgs/im001.jpg' %}" alt="">
	</div>
	<img src="{% static 'imgsd/im002.jpg' %}" alt="">
</body>
</html>

Py1809Project/FireFish/Bocke/templates/Bocke/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Hans</title>
	{% load static %}
	<link rel="stylesheet" type="text/css" href="{% static 'Bocke/css/Hans.css' %}">


</head>
<body>
	<div id="a">
		<div id="a1" >
		<h1>万万没想到</h1>
		<h2>登录</h2>
		<form action="{% url 'Bocke:Hans'%}"  method="post">
			{%csrf_token%}
			用户名：<input type="text" class="s1" placeholder="4-8个字符" name="username" autocomplete="off" required autofocus value="">
			<br>
			&nbsp;&nbsp;密&nbsp;码&nbsp;：<input type="password" class="s1" placeholder="8-16位" required name="pwd" value="">
			<br>
			<br>
			<div id="aa1">
				<input type="submit" value="登录">
			&nbsp;&nbsp;&nbsp;<input type="reset" value="重置">
			<br>
			<h5 color="red">{{msg}}</h5>
			</div>

		</form>
	</div>
	</div>
	
</body>
</html>

Py1809Project/FireFish/Bocke/templates/Bocke/login_success.html
<!DOCTYPE html>
<html lang="en">
{% block head %}
<head>
    <meta charset="UTF-8">
    <title>Hans</title>
	{% load static %}
	<link rel="stylesheet" type="text/css" href="{% static 'Bocke/css/Hans.css' %}">
	<style type="text/css">

		#a{position:absolute;
			background:none;
		}
		#ww1{
			display:none
		}
		.s1{
			position:absolute;
			left: 10px;
			top:60px;
		}
		.ss1{
			position:absolute;
			right: 10px;
			top:60px;
		}
		.sss1{
			margin: 5px auto;
		}
		.i1{
			text-overflow:ellipsis;
			display:none;
			overflow:hidden;
			width:20px;
			margin:0px;
			border:0px;
		}
		.i2{
			position:relitive;
			width:80px;
			overflow:hidden;
		}
		.ii1{
			position:relative;
			float:left
		}

	</style>
</head>
{% endblock %}
<body>

	<div id="a">
		{% block con_head %}
		<h3>{{user.username}}的空间</h3>
		{% endblock %}
			<div id="a1">
				{% block table %}
				<h4>文章列表:</h4>
				<table  class="sss1" border="2" cellspacing="1" cellpadding="1">
					<tr><th width=80 >title</th><th width=180>创建时间</th><th width=80 >查看</th></tr>
					{% for i in arts %}
					<tr >
						<td>{{i.artname}}</td><td >{{i.ctime}}</td>
						<td class="i2" width=80 height=50 >
						<form width=80  action="{% url 'Bocke:read' %}" method="post">
							{% csrf_token %}
							<input class="i1"  type="text" name="con" value={{i.arttext}}>
							<input class="i1"  type="text" name="atitle" value={{i.artname}}>
							<input class="i1"  type="text" name="ct" value={{i.ctime}}>
							<input class="i1"  type="text" name="author" value={{user.username}}>
							<input class="ii1" type="submit" value="查看">
						</form>
					</td></tr>
					{% empty %}
					没文章。。。。好尴尬
					{% endfor %}
				</table>
				<h4>文章总数{{sum}}</h4>
				<a href="{% url 'Bocke:writer' %}"><h3>写文章</h3></a>

				<form action="{% url 'Bocke:Hans1' %}" method="post">
					{% csrf_token %}
					<input type="number" hidden name="auth" value="{{user.id}}">
					标题:<input type="text"  placeholder="标题不超过12个字符" required maxlength="12" name="title" value="">
					<br><br>
					<textarea name="con" placeholder="内容超过255个字符" maxlength="180" cols="30" rows="10"></textarea>
					<input id="su1" type="submit" value="提交">
				</form>
				{% endblock %}

			</div>
		<img class="s1" src="{% static 'Bocke/imgs/run.gif' %}" alt="">
		<img class="ss1" src="{% static 'Bocke/imgs/run.gif' %}" alt="">


	</div>
</body>
</html>

Py1809Project/FireFish/Bocke/templates/Bocke/regist_success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Hans</title>
	{% load static %}
	<link rel="stylesheet" type="text/css" href="{% static 'Bocke/css/Hans.css' %}">

</head>
<body>
	<div id="a">
		<div id="a1" >
			<h1>万万没想到</h1>
			<h2 color="red">注册成功，您可以去登陆啦</h2>
			<a href="{% url 'Bocke:login' %}">登录</a>
		</div>
	</div>
	
</body>
</html>

Py1809Project/FireFish/Bocke/templates/Bocke/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Hans</title>
	{% load static %}
	<link rel="stylesheet" type="text/css" href="{% static 'Bocke/css/Hans.css' %}">
</head>
<body>
	<div id="a">
		<div id="a1">
		<h1>万万没想到</h1>
		<h2>注册</h2>
		<form action="{% url 'Bocke:success' %}" method="post">
			{% csrf_token %}
			用户名：<input type="text" class="s1" placeholder="4-8个字符" required autofocus name="username" autocomplete="off"  value="">
			<br>
			&nbsp;&nbsp;密&nbsp;码&nbsp;：<input type="password" class="s1" placeholder="8-16个数字、字母或下划线" required name="pwd" value="">
			<br>
			&nbsp;&nbsp;年&nbsp;龄&nbsp;：<input type="number" class="s1" placeholder="8-120" autocomplete="off" name="age" value="">
			<br>
			<div id="aa1">
				<input type="submit" value="注册">
			&nbsp;&nbsp;&nbsp;<input type="reset" value="重置">
			<br>
			<h5 color="red">{{msg}}</h5>
			</div>
		</form>
	</div>
	</div>
	
</body>
</html>