Py1809Project/iceberg/cars/urls.py
from .import views
from django.conf.urls import url

urlpatterns = [
        url(r'^addCar/$', views.addCar, name='addCar'),
        url(r'^carorder/$', views.carorder, name='carorder'),
        url(r'^updatelist/$', views.updatelist, name='updatelist'),
        url(r'^myorder/$', views.myorder, name='myorder'),
        url(r'^paysgoods/$', views.paysgoods, name='paysgoods'),
    ]

Py1809Project/iceberg/goods/urls.py
from .import views
from django.conf.urls import url

urlpatterns = [
    url(r'^upgoods/$', views.upgoods, name='upgoods'),
    url(r'^goodsinfo/$', views.goodsinfo, name='goodsinfo'),
    url(r'^updownGoods/$', views.updownGoods, name='updownGoods'),
    url(r'^updategoods/$', views.updategoods, name='updategoods'),
    url(r'^detailinfo/$', views.detailinfo, name='detailinfo'),
    url(r'^single/$', views.single, name='single'),

]

Py1809Project/iceberg/iceberg/urls.py
from django.conf.urls import url, include
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^iceberg/', include('users.urls',namespace='users')),
    url(r'^iceberg/', include('store.urls',namespace='store')),
    url(r'^iceberg/', include('goods.urls',namespace='goods')),
    url(r'^iceberg/', include('cars.urls',namespace='cars')),
]

Py1809Project/iceberg/store/urls.py
from .import views
from django.conf.urls import url

urlpatterns = [
    url(r'^women/$', views.women, name='women'),
    url(r'^men/$', views.men, name='men'),
    url(r'^collection/$', views.collection, name='collection'),
    url(r'^(?P<id>\d+)/addcollect/$', views.addcollect, name='addcollect'),
    url(r'^colldel/$', views.colldel, name='colldel'),
    url(r"^mystore/$", views.mystore, name="mystore"),
    url(r"^updatestore/$", views.updatestore, name="updatestore"),

]

Py1809Project/iceberg/users/urls.py
from .import views
from django.conf.urls import url

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^register/$', views.register, name='register'),
    url(r'^logins/$', views.logins, name='logins'),
    url(r"^active/$", views.actives, name="active"),
    url(r"^yanzheng/$", views.yanzheng, name="yanzheng"),
    url(r"^userinfor/$", views.userinfor, name="userinfor"),
    url(r"^updateuser/$", views.updateuser, name="updateuser"),
    url(r"^baseinfo/$", views.baseinfo, name="baseinfo"),
    url(r"^createstore/$", views.createstore, name="createstore"),
    url(r"^addaddress/$", views.addaddress, name="addaddress"),
    url(r"^updateaddre/$", views.updateaddre, name="updateaddre"),
    url(r"^ordered/$", views.ordered, name="ordered"),
    url(r"^quite/$", views.quite, name="quite"),
]

Py1809Project/iceberg/goods/models.py
from django.db import models
from store.models import stores
from users.models import Users
# Create your models here.


class goods(models.Model):
    id = models.AutoField(primary_key=True)
    waresname = models.CharField(max_length=30,verbose_name='商品名字')
    waresinfo = models.CharField(max_length=200,verbose_name='商品详情')
    waressize = models.CharField(max_length=4,verbose_name='商品尺码')
    waresstock = models.PositiveIntegerField(verbose_name='商品库存',default=0)
    warescount = models.PositiveIntegerField(verbose_name='商品销量',default=0)
    waresprice = models.FloatField(verbose_name='商品价格', max_length=7)
    borntime = models.DateTimeField(verbose_name='上架时间', auto_now_add=True)
    warestatus = models.BooleanField(verbose_name='商品状态',default=True)
    forgoo = models.ForeignKey(stores, on_delete=models.CASCADE)

class category(models.Model):
    id = models.AutoField(primary_key=True)
    category1 = models.CharField(max_length=20,verbose_name='男士/女士')
    category2 = models.CharField(max_length=20,verbose_name='季节')
    forcat = models.ForeignKey(goods, on_delete=models.CASCADE)

class goodsimgs(models.Model):
    id = models.AutoField(primary_key=True)
    imag0 = models.ImageField(upload_to='static/upload/goods', verbose_name='商品图片')
    forimg = models.ForeignKey(goods, on_delete=models.CASCADE)


# 收藏
class cllocter(models.Model):
    id = models.AutoField(primary_key=True)
    goodsid = models.IntegerField(verbose_name='商品id')
    forcll = models.ForeignKey(Users, on_delete=models.CASCADE)

Py1809Project/iceberg/store/models.py
from django.db import models
from users.models import Users

# Create your models here.

class stores(models.Model):
    id = models.AutoField(primary_key=True)
    storename = models.CharField(max_length=20)
    storephoto = models.ImageField(upload_to='static/upload/store', validators='店铺图片', blank=True)
    reg_time = models.DateTimeField(verbose_name='营业时间', auto_now_add=True)
    storeinfo = models.CharField(max_length=100, blank=True)
    states = models.BooleanField(verbose_name='营业状态:', default=False)
    masters = models.ForeignKey(Users, on_delete=models.CASCADE)

Py1809Project/iceberg/store/views.py
from django.shortcuts import render, HttpResponse, redirect
from . import models
import hashlib
from django.core.cache import cache
from goods.models import goods,category,cllocter


# 导入分页模块
from django.core.paginator import Paginator
from django.conf import settings
# Create your views here.


# 我的某一个项目
def mystore(request):
    if request.method == 'GET':
        # 传来某一个店铺的id
        if request.GET.get('sid'):
            request.session['store'] = models.stores.objects.get(id=int(request.GET['sid']))
            goodsli = cache.get('goodsli')
            if goodsli is None:
                goodsli = goods.objects.filter(forgoo=request.session['store'])
                cache.set('goodsli', goodsli, 60*5)
        return render(request, 'store/mystore.html')
    elif request.method == 'POST':
        return render(request, 'store/mystore.html')


# 修改店铺信息
def updatestore(request):
    if request.method == 'GET':
        return render(request, 'store/updatestore.html')
    elif request.method == 'POST':
        password = request.POST["password"]
        md = hashlib.md5()
        md.update(password.encode('utf8'))
        pwds = md.hexdigest()
        user = request.session['user']
        if user.pwd != pwds:
            return render(request, 'store/updatestore.html', {'msg': '密码输入错误'})
        storename = request.POST["storename"]
        info = request.POST["info"]
        inlineRadioOptions = request.POST["inlineRadioOptions"]
        # 修改店铺状态
        if inlineRadioOptions == 'True':
            states = True
        elif inlineRadioOptions == 'False':
            states = False
        store2 = request.session['store']
        store2.storename = storename
        store2.storeinfo = info
        store2.states = states
        try:
            storeimg = request.FILES['storeimg']
            store2.storephoto = storeimg
        except:
            pass
        store2.save()
        if inlineRadioOptions != '':
            # 更新页面，避免商店状态的变动导致的错误。

            stores2 = models.stores.objects.filter(states=True)
            goodsall = []
            for i in stores2:
                goodsall.extend(goods.objects.filter(warestatus=True, forgoo=i))
            cache.set("goodsall", goodsall, 60*5)
            temp1 = []
            temp2 = []
            for u in goodsall:
                categorys = category.objects.get(forcat=u)
                if categorys.category1 == '男士':
                    temp1.append(u)
                else:
                    temp2.append(u)
            cache.set('mens', temp1, 60*5)
            cache.set('womens', temp2, 60*5)
        # 更新店铺信息
        request.session['store'] = store2
        store1 = models.stores.objects.filter(masters=request.session['user'])
        request.session['storelis'] = store1
        return render(request, 'store/mystore.html')

# 男装页面
def men(request):
    mens = cache.get("mens")
    if mens is None:
        # 筛选出男/女士商品
        mens = []
        womens = []
        goodsall = cache.get('goodsall')
        if goodsall is None:
            stores2 = models.stores.objects.filter(states=True)
            goodsall = []
            for i in stores2:
                goodsall.extend(goods.objects.filter(warestatus=True, forgoo=i))
            cache.set('goodsall', goodsall, 60 * 5)
        for u in goodsall:
            categorys = category.objects.get(forcat=u)
            if categorys.category1 == '男士':
                mens.append(u)
            else:
                womens.append(u)
        cache.set('mens', mens, 60 * 5)
        cache.set('womens', womens, 60 * 5)
    # 分页
    pagesize = settings.PAGESIZE
    paginator = Paginator(mens, pagesize + 2)
    # 获取当前页的页码
    pagenum = request.GET.get('pagenum', default=1)
    page = paginator.page(int(pagenum))
    return render(request, 'store/men.html', {'paginator':paginator, 'page':page})

# 女装页面
def women(request):
    womens = cache.get('womens')
    if womens is None:
        # 筛选出男/女士商品
        mens = []
        womens = []
        goodsall = cache.get('goodsall')
        if goodsall is None:
            stores2 = models.stores.objects.filter(states=True)
            goodsall = []
            for i in stores2:
                goodsall.extend(goods.objects.filter(warestatus=True, forgoo=i))
            cache.set('goodsall', goodsall, 60 * 5)
        for u in goodsall:
            categorys = category.objects.get(forcat=u)
            if categorys.category1 == '男士':
                mens.append(u)
            else:
                womens.append(u)
        cache.set('mens', mens, 60 * 5)
        cache.set('womens', womens, 60 * 5)
    # 分页
    pagesize = settings.PAGESIZE
    paginator = Paginator(womens, pagesize+2)
    # 获取当前页的页码
    pagenum = request.GET.get('pagenum', default=1)
    page = paginator.page(int(pagenum))
    return render(request, 'store/women.html', {'paginator':paginator, 'page': page})


# 收藏页面
def collection(request):
    # 判断有没有登陆
    if 'user' not in request.session:
        return redirect('users:logins')
    colllist = cllocter.objects.filter(forcll=request.session['user'])
    request.session['colllist'] = []
    for i in colllist:
        wares1 = goods.objects.get(id=i.goodsid)
        request.session['colllist'].append(wares1)
    return render(request, 'store/collection.html')


def addcollect(request,id):
    # 判断有没有登陆
    if 'user' not in request.session:
        return redirect('users:logins')
    # 添加收藏
    clllos1 = cllocter.objects.filter(goodsid=id, forcll=request.session['user'])
    if not clllos1.exists():
        cllos = cllocter(goodsid=id, forcll=request.session['user'])
        cllos.save()
        mas = '收藏成功'
    else:
        mas = '收藏库已有该商品'
    return HttpResponse(mas)


def colldel(request):
    # 取消收藏
    sid = request.GET['seach']
    clllos = cllocter.objects.get(goodsid=sid, forcll=request.session['user'])
    clllos.delete()
    return redirect('store:collection')

Py1809Project/iceberg/store/templates/store/collection.html
<!DOCTYPE html>
<html>
<head>
    <title>iceberg</title>

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->

    <!-- Custom Theme files -->
    <!--theme-style-->
    <link href="/static/css/style.css" rel="stylesheet" type="text/css" media="all"/>
    <script src="/static/js/jquery.min.js"></script>
    <link href="/static/css/bootstrap.css" rel="stylesheet" type="text/css" media="all"/>
    <!--//theme-style-->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta name="keywords" content="Fashion Store Responsive web template, Bootstrap Web Templates, Flat Web Templates, Andriod Compatible web template,
Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyErricsson, Motorola web design"/>
    <script type="application/x-javascript">
         addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); }

    </script>
    <!--fonts-->
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700,800' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Oswald:400,700,300' rel='stylesheet' type='text/css'>
    <!--//fonts-->
    <style>
		#dl{
			position:relative;
			left:350px;
		}



    </style>
    <link rel="stylesheet" href="/static/css/etalage.css">
    <script src="/static/js/jquery.etalage.min.js"></script>

    <script>
			jQuery(document).ready(function($){

				$('#etalage').etalage({
					thumb_image_width: 300,
					thumb_image_height: 400,
					source_image_width: 900,
					source_image_height: 1200,
					show_hint: true,
					click_callback: function(image_anchor, instance_id){
						alert('Callback example:\nYou clicked on an image with the anchor: "'+image_anchor+'"\n(in Etalage instance: "'+instance_id+'")');
					}
				});

			});


    </script>
    <!-- the jScrollPane script -->
    <script type="text/javascript" src="/static/js/jquery.jscrollpane.min.js"></script>
    <script type="text/javascript" id="sourcecode">
			$(function()
			{
				$('.scroll-pane').jScrollPane();
			});


    </script>
</head>
<body>
<!--header-->
<div class="header">
    <div class="header-top">
        <div class="container">
            <div class="header-grid">
                <ul>
                    <li><a href="articles.html" class="scroll">Articles</a></li>
                    <li><a href="contact.html" class="scroll">Contact </a></li>
                    <li><a href="privacy.html" class="scroll">Privacy</a></li>
                    <li><a href="#" class="scroll">Terms</a></li>
                </ul>
            </div>
            <div class="header-grid-right" id="dl">
                {% if request.session.user is None %}
                <a href="{% url 'users:logins' %}" class="sign-up">登录</a>
                <label>|</label>
                <a href="{% url 'users:register' %}" class="sign-up">注册</a>
                {% else %}
                <a href="{% url 'users:userinfor' %}" class="scroll"
                   style="color:red">{{request.session.user.pickname}}</a>
                <img width=60 height=60 class="img-circle" src='/{{request.session.user.header}}' alt="">
                <span><a href="{% url 'users:quite' %}" style="color:red">退出</a></span>
                {% endif %}
            </div>
            <div class="clearfix"></div>

        </div>
    </div>
    <div class="container">
        <div class="header-bottom">
            <div class="logo">
                <a href="index.html"><img src="/static/images/logo.png" alt=" "></a>
            </div>
            <div class="ad-right">
                <img src="/static/images/ad.png" alt=" ">
            </div>
            <div class="clearfix"></div>
        </div>
        <div class="header-bottom-bottom">
            <div class="top-nav">
                <span class="menu"> </span>
                <ul>
                    <li><a href="{% url 'users:index' %}">HOME </a></li>
                    <li><a href="{% url 'store:men' %}">男装</a></li>
                    <li><a href="{% url 'store:women' %}">女装</a></li>
                    <li class="active"><a href="{% url 'store:collection' %}">收藏</a></li>
                </ul>
                <script>
					$("span.menu").click(function(){
						$(".top-nav ul").slideToggle(500, function(){
						});
					});


                </script>
                <div class="clearfix"></div>
            </div>
            <div class="search">
                <form>
                    <input type="text" value="Search" onfocus="this.value = '';"
                           onblur="if (this.value == '') {this.value = '';}">
                    <input type="submit" value="">
                </form>
            </div>
            <div class="clearfix"></div>
        </div>
    </div>
</div>
<!--content-->
<div class="content">
    <div class="container">
        {% for u in request.session.colllist %}
        <div class="col-md-4 you-para">
            <a href="/iceberg/single/?seach={{u.id}}">
                <img class="pic-in" width=160 height=200 src="/{{u.goodsimgs_set.all.first.imag0}}"
                     alt=" ">
            </a>
            <div class="you-in" style="position:relative;right:2px;top:-40px;">
                <span>15<label>%</label></span>
                <small>off</small>
            </div>
            <p>{{ u.waresname }}</p>
            <span>￥{{ u.waresprice}}  |
            <a href="/iceberg/colldel/?seach={{u.id}}">
                <button type="button" class="btn-group btn-group-xs addcart" goodsid={{u.id}}>
                  <span class="glyphicon glyphicon-heart" aria-hidden="true">取消收藏</span>
                </button>
            </a>
        </span>
        </div>
        {% empty %}
            😔，您还没有收藏
        {% endfor %}
    </div>

</div>


<div class="footer">
		<div class="container">
				<div class="footer-class">
				<div class="class-footer">
					<ul>
						<li ><a href="index.html" class="scroll">HOME </a><label>|</label></li>
						<li><a href="men.html" class="scroll">MEN</a><label>|</label></li>
						<li><a href="women.html" class="scroll">WOMEN</a><label>|</label></li>
						<li><a href="collection.html" class="scroll">COLLECTION</a><label>|</label></li>
						<li><a href="collection.html" class="scroll">STORE PRODUCTS</a><label>|</label></li>
						<li><a href="collection.html" class="scroll">LATEST  PRODUCT</a></li>
					</ul>
					 <p class="footer-grid">Copyright &copy; 2015.Company name All rights reserved.More Templates <a href="http://www.cssmoban.com/" target="_blank" title="模板之家">模板之家</a> - Collect from <a href="http://www.cssmoban.com/" title="网页模板" target="_blank">网页模板</a></p>
				</div>
				<div class="footer-left">
					<a href="index.html"><img src="/static/images/logo1.png" alt=" " /></a>
				</div>
				<div class="clearfix"> </div>
			 	</div>
		 </div>
	</div>

</body>
</html>

Py1809Project/iceberg/store/templates/store/men.html
<!DOCTYPE html>
<html>
<head>
<title>Men</title>
<link href="/static/css/bootstrap.css" rel="stylesheet" type="text/css" media="all" />
<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="/static/js/jquery.min.js"></script>
<!-- Custom Theme files -->
<!--theme-style-->
<link href="/static/css/style.css" rel="stylesheet" type="text/css" media="all" />	
<!--//theme-style-->
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="keywords" content="Fashion Store Responsive web template, Bootstrap Web Templates, Flat Web Templates, Andriod Compatible web template, 
Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyErricsson, Motorola web design" />
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
<!--fonts-->
	<style>
		#dl{
			position:relative;
			left:350px;
		}

	</style>
<link href='https://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700,800' rel='stylesheet' type='text/css'>
<link href='https://fonts.googleapis.com/css?family=Oswald:400,700,300' rel='stylesheet' type='text/css'>
<!--//fonts-->
</head>
<body> 
	  <!--header-->
		<div class="header">
		<div class="header-top">
			<div class="container">
				<div class="header-grid">
					<ul>
						<li  ><a href="#" class="scroll">Articles</a></li>
						<li><a href="#" class="scroll">Contact  </a></li>
						<li><a href="{% url 'users:userinfor' %}" class="scroll">我的</a></li>
						<li><a href="#" class="scroll">Terms</a></li>						
					</ul>
				</div>
				<div class="header-grid-right" id="dl">
					{% if request.session.user is None %}
					<a href="{% url 'users:logins' %}" class="sign-up" >登录</a>
					<label>|</label>
					<a href="{% url 'users:register' %}" class="sign-up">注册</a>
					{% else %}
					<a href="{% url 'users:userinfor' %}" class="scroll" style="color:red">{{request.session.user.pickname}}</a>
					<img width=60 height=60 class="img-circle" src='/{{request.session.user.header}}' alt="">
					<span><a href="{% url 'users:quite' %}" style="color:red">退出</a></span>
					{% endif %}
				</div>
				<div class="clearfix"> </div>
			</div>
		</div>
		<div class="container">
		<div class="header-bottom">			
				<div class="logo">
					<a href="index.html"><img src="/static/images/logo.png" alt=" " ></a>
				</div>
					<div class="ad-right">
					<img src="/static/images/ad.png" alt=" " >
				</div>
				<div class="clearfix"> </div>
			</div>	
			<div class="header-bottom-bottom">
				<div class="top-nav">
					<span class="menu"> </span>
					<ul>
						<li ><a href="{% url 'users:index' %}">HOME </a></li>
						<li class="active"><a href="{% url 'store:men' %}" >男装</a></li>
						<li><a href="{% url 'store:women' %}" >女装</a></li>
						<li><a href="{% url 'store:collection' %}">我的收藏</a></li>
                    	<li><a href="{% url 'cars:carorder' %}">购物车</a></li>
					</ul>
					<div class="clearfix"> </div>
				<script>
					$("span.menu").click(function(){
						$(".top-nav ul").slideToggle(500, function(){
						});
					});
				</script>
					
				</div>
				<div class="search">
					<form>
						<input type="text" value="Search" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = '';}" >
						<input type="submit"  value="">
					</form>
				</div>
				<div class="clearfix"> </div>
				</div>
		</div>
	</div>
	<!--content-->
	<div class="content">
		<div class="container">
			<div class="  col-m-on">
				<!---->
				<div class="in-line">
					<div class="para-all">
						<h3>LATEST  ARRIVALS</h3>
						<p>Check our all latest products in this section.</p>
					</div>
					<div class="lady-on">
						{% for u in page %}
						<div class="col-md-4 you-para">
								<a href="/iceberg/single/?seach={{u.id}}">
									<img class="pic-in" width=160 height=200 src="/{{u.goodsimgs_set.all.first.imag0}}" alt=" " >
								</a>
							<div class="you-in" style="position:relative;right:2px;top:-40px;">
								<span>15<label>%</label></span>
							<small>off</small>
							</div>
							<p>{{ u.waresname }}</p>
								<span>￥{{ u.waresprice}}  |
									<button type="button" class="btn-group btn-group-xs addcart" goodsid={{u.id}}>
                                         <span class="glyphicon glyphicon-heart" aria-hidden="true">收藏</span>
                                    </button>
								</span>

						</div>
						{% endfor %}

						<div class="col-md-4 you-para">
                            <nav aria-label="Page navigation">
                                <ul class="pagination">
                                    <li><a href="/iceberg/men/?pagenum=1">首页</a></li>

                                    {% if page.has_previous %}
                                    <li><a href="/iceberg/men/?pagenum={{page.previous_page_number}}" aria-label="Previous">
                                            <span aria-hidden="true">&laquo;</span>
                                        </a>
                                    </li>
                                    {% endif %}

                                    {% for i in paginator.page_range %}
                                        {% if page.number == i %}
                                            <li class="active"><a href="/iceberg/men/?pagenum={{i}}" >{{i}}</a></li>
                                        {% else %}
                                            <li><a href="/iceberg/men/?pagenum={{i}}">{{i}}</a></li>
                                        {% endif %}
                                    {% endfor %}
                                    {% if page.has_next %}
                                    <li><a href="/iceberg/men/?pagenum={{page.next_page_number}}" aria-label="Next">
                                            <span aria-hidden="true">&raquo;</span>
                                        </a>
                                    </li>
                                    {% endif %}

                                    <li><a href="/iceberg/men/?pagenum={{paginator.num_pages}}">尾页</a></li>
                                </ul>
                            </nav>
                    </div>

						<div class="clearfix"> </div>
					</div>
				</div>
			</div>
			<!---->
			<div class="lady-in-on">
			<div class="buy-an">
						<h3>OTHER PRODUCTS</h3>
						<p>Check our all latest products in this section.</p>
					</div>
					<ul id="flexiselDemo1">			
				<li><a href="#"><img class="img-responsive women" src="/static/images/faa.jpg" alt=""></a>
				<div class="hide-in">
				<p>Premium Denim Women's Hidden</p>
				<span>$179.00  |  <a href="#">Buy Now</a></span>
				</div></li>
				<li><a href="#"><img class="img-responsive women" src="/static/images/faa1.jpg" alt=""></a>
				<div class="hide-in">
				<p>Premium Denim Women's Hidden</p>
				<span>$179.00  |  <a href="#">Buy Now</a></span>
				</div></li>
				<li><a href="#"><img class="img-responsive women" src="/static/images/faa.jpg" alt=""></a>
				<div class="hide-in">
				<p>Premium Denim Women's Hidden</p>
				<span>$179.00  |  <a href="#">Buy Now </a></span>
				</div></li>
				<li><a href="#"><img class="img-responsive women" src="/static/images/faa1.jpg" alt=""></a>
				<div class="hide-in">
				<p>Premium Denim Women's Hidden</p>
				<span>$179.00  |  <a href="#">Buy Now</a></span>
				</div></a></li>
            </ul>
            		<script type="text/javascript">
		$(window).load(function() {
			$("#flexiselDemo1").flexisel({
				visibleItems: 4,
				animationSpeed: 1000,
				autoPlay: true,
				autoPlaySpeed: 3000,    		
				pauseOnHover: true,
				enableResponsiveBreakpoints: true,
		    	responsiveBreakpoints: { 
		    		portrait: { 
		    			changePoint:480,
		    			visibleItems: 1
		    		}, 
		    		landscape: { 
		    			changePoint:640,
		    			visibleItems: 2
		    		},
		    		tablet: { 
		    			changePoint:768,
		    			visibleItems: 3
		    		}
		    	}
		    });
		    
		});
	</script>
	<script type="text/javascript" src="/static/js/jquery.flexisel.js"></script>
		</div>
	</div>
	</div>
	<!---->
	<div class="footer">
		<div class="container">
				<div class="footer-class">
				<div class="class-footer">
					<ul>
						<li ><a href="index.html" class="scroll">HOME </a><label>|</label></li>
						<li><a href="men.html" class="scroll">MEN</a><label>|</label></li>
						<li><a href="women.html" class="scroll">WOMEN</a><label>|</label></li>
						<li><a href="collection.html" class="scroll">COLLECTION</a><label>|</label></li>
						<li><a href="collection.html" class="scroll">STORE PRODUCTS</a><label>|</label></li>
						<li><a href="collection.html" class="scroll">LATEST  PRODUCT</a></li>
					</ul>
					 <p class="footer-grid">Copyright &copy; 2015.Company name All rights reserved.More Templates <a href="http://www.cssmoban.com/" target="_blank" title="模板之家">模板之家</a> - Collect from <a href="http://www.cssmoban.com/" title="网页模板" target="_blank">网页模板</a></p>
				</div>	 
				<div class="footer-left">
					<a href="index.html"><img src="/static/images/logo1.png" alt=" " ></a>
				</div> 
				<div class="clearfix"> </div>
			 	</div>
		 </div>
	</div>
<script>
	{% if request.session.user is None %}
    {% else %}
    //利用ajax异步涮新,添加收藏
    $('.addcart').click(function () {
        var $goodsid = $(this).attr('goodsid')

        $.ajax({
            type:'get',
            url:'/iceberg/'+ $goodsid + '/addcollect/',
            success:function (response) {
                alert(response)
            },
            error:function () {
                alert('收藏失败')
            }
        })
    })
	{% endif %}
</script>
</body>
</html>